### ISSUE TITLE
Installing lpy from Source / Using openalea.lpy in Python Script

### ISSUE THREAD

**Issue by deltayoung** [fredboudon/lpy#26]
We had developed our script in the past based on Python 2.7.6 openalea.lpy (http://openalea.gforge.inria.fr/dokuwiki/doku.php) 
. Now it seems that our code is pretty much obsolete as most involved packages are deprecated by now. May I confirm with you that one should no longer refer to http://openalea.gforge.inria.fr/dokuwiki/doku.php for installing Lpy? It might be good to mark it so on the website to avoid confusion with the current github lpy version. 

This github lpy code seems to be Python 3 based, so we would like to port our code accordingly (Windows platform) to use openalea.lpy module in our code (https://lpy.readthedocs.io/en/latest/user/integration.html), but so far we have no luck in installing it from the source based on https://lpy.readthedocs.io/en/latest/user/installing.html#installing-from-sources. We encountered error during the lpy compilation at the "cmake" step 
cmake -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
      -DCMAKE_PREFIX_PATH=${CONDA_PREFIX} \
      -DCMAKE_BUILD_TYPE=Release  \
      -LAH ..
which was executed from within the "<git-cloned-lpy-directory>/build". The error message is: "CMake Error: The source directory "D:/Code/lpy/build/text" does not exist." I only have "D:/Code/lpy/test" directory by the cloned lpy folder. Please advise how to proceed with this? Thank you!

**Comment by fredboudon** [comment]
I confirm you that we are in the process of porting all openalea modules to python 3 and propose a new installation procedure based on conda. As it is not fully ported, we did not updated the openalea website yet.
For your build error, this is strange error as the build should not depend of test.
I'm not sure to see from where it comes. 
Can't you use the built packages ?
