### ISSUE TITLE
How to use the GetPos and other requests?

### ISSUE THREAD

**Issue by ChrisPHP** [fredboudon/lpy#27]
Hello,

I'm trying to get the current vector position of the turtle and save it in a variable for later use how can this be achieved in Lpy?

Thank you.

**Comment by KatherineJames** [comment]
This is a simple example to get started with:

SomeExample(a:)
  nproduce ?P(0,0,0)MyExampleSphere(a)  
	  
?P(x,y,z)MyExampleSphere(size):
  print(x,y,z)
  nproduce @O(size)
