### ISSUE TITLE
Does Lpy have an API for exporting 3d files?

### ISSUE THREAD

**Issue by Jiang2019Code** [fredboudon/lpy#42]

**Comment by fredboudon** [comment]
No sorry. For now, just export to obj file are supported.

**Comment by Jiang2019Code** [comment]
How can we export to obj?Thanks.


------------------ Original ------------------
From: Frederic Boudon ***@***.***&gt;
Date: Fri,Apr 15,2022 4:23 PM
To: fredboudon/lpy ***@***.***&gt;
Cc: Jiang2019Code ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [fredboudon/lpy] Does Lpy have an API for exporting 3d files?(Issue #42)





 
No sorry. For now, just export to obj file are supported.
