### ISSUE TITLE
Interaction with environment

### ISSUE THREAD

**Issue by s-n-naik** [fredboudon/lpy#43]
Is there a way in L-py to ensure that tree branches do not overlap, or model interaction with the environment e.g. nearby trees / a wall?

**Comment by fredboudon** [comment]
You should use the ?P module to get the position of each module and determine if you should for instance remove it.
See for instance, the following example:
https://github.com/fredboudon/lpy/blob/master/share/tutorial/06%20-%20environement/01%20-%20open-lsystem-simple-growth.lpy
